// packages/svelte/src/FabButton.svelte
<script lang="ts">
  import { createEventDispatcher, tick } from "svelte"
  import {
    getEnabledSectionIndices,
    getFabButtonClasses,
    getFabButtonCssVars,
    getNavigationCommand,
    resolveSectionIndex,
    getSectionClasses,
    normalizeSections
  } from "@rezafab/fab-button-core"
  import type { FabButtonProps, FabButtonSection } from "./types"

  import "@rezafab/fab-button-styles/style.css"

  export let sections: FabButtonSection[] = []
  export let variant: NonNullable<FabButtonProps["variant"]> = "default"
  export let size: NonNullable<FabButtonProps["size"]> = "md"
  export let shape: NonNullable<FabButtonProps["shape"]> = "rounded"
  export let layout: NonNullable<FabButtonProps["layout"]> = "flex"
  export let columns: FabButtonProps["columns"] = undefined
  export let rows: FabButtonProps["rows"] = undefined
  export let gap: FabButtonProps["gap"] = undefined
  export let className: FabButtonProps["className"] = undefined
  export let style: FabButtonProps["style"] = undefined
  export let unstyled = false
  export let disabled = false
  export let loading = false
  export let ariaLabel: FabButtonProps["ariaLabel"] = undefined
  export let keyboardNavigation: NonNullable<FabButtonProps["keyboardNavigation"]> = "tab"
  export let keyboardOrientation: FabButtonProps["keyboardOrientation"] = undefined
  export let loopNavigation = true
  export let onClick: FabButtonProps["onClick"] = undefined

  const dispatch = createEventDispatcher<{
    click: MouseEvent
    sectionClick: { key: string; event: MouseEvent }
  }>()

  const toStyleString = (vars: Record<string, string>) =>
    Object.entries(vars)
      .filter(([, value]) => value !== "")
      .map(([key, value]) => `${key}: ${value}`)
      .join("; ")

  let activeIndex = -1
  let sectionRefs: Array<HTMLButtonElement | null> = []

  $: normalizedSections = normalizeSections(sections ?? [])
  $: hasSectionActions = normalizedSections.some((section) => Boolean(section.onClick))
  $: isDisabled = disabled || loading
  $: toolbarMode = hasSectionActions && keyboardNavigation === "toolbar"
  $: resolvedKeyboardOrientation = keyboardOrientation ?? (layout === "grid" ? "both" : "horizontal")
  $: enabledIndices = getEnabledSectionIndices(normalizedSections, isDisabled)
  $: if (toolbarMode) {
    if (!enabledIndices.length) {
      activeIndex = -1
    } else if (!enabledIndices.includes(activeIndex)) {
      activeIndex = enabledIndices[0]
    }
  }
  $: styleVars = getFabButtonCssVars({ columns, rows, gap })
  $: rootClassName = unstyled
    ? className
    : getFabButtonClasses({
        className,
        layout,
        size,
        shape,
        variant,
        disabled: isDisabled,
        loading
      })
  $: rootStyle = [toStyleString(styleVars), style].filter(Boolean).join("; ")

  const handleRootClick = (event: MouseEvent) => {
    onClick?.(event)
    dispatch("click", event)
  }

  const handleSectionClick = (section: FabButtonSection, event: MouseEvent) => {
    section.onClick?.(event)
    dispatch("sectionClick", { key: section.key, event })
  }

  const focusSection = async (index: number) => {
    await tick()
    sectionRefs[index]?.focus()
  }

  const registerSection = (node: HTMLButtonElement, index: number) => {
    sectionRefs[index] = node
    return {
      destroy: () => {
        if (sectionRefs[index] === node) sectionRefs[index] = null
      }
    }
  }

  const handleToolbarKeydown = (event: KeyboardEvent) => {
    if (!toolbarMode || !enabledIndices.length) return

    const command = getNavigationCommand(event.key, resolvedKeyboardOrientation)
    if (!command) return

    const target = event.target as HTMLElement | null
    const sectionButton = target?.closest<HTMLButtonElement>("button[data-section-index]")
    if (!sectionButton) return

    const indexValue = Number(sectionButton.dataset.sectionIndex)
    const currentIndex = Number.isNaN(indexValue) ? activeIndex : indexValue
    const nextIndex = resolveSectionIndex({
      command,
      currentIndex,
      enabledIndices,
      loop: loopNavigation
    })
    if (nextIndex === null) return

    event.preventDefault()
    activeIndex = nextIndex
    focusSection(nextIndex)
  }
</script>

{#if hasSectionActions}
  <div
    class={rootClassName}
    style={rootStyle}
    role={toolbarMode ? "toolbar" : "group"}
    aria-label={ariaLabel}
    aria-orientation={toolbarMode && resolvedKeyboardOrientation !== "both"
      ? resolvedKeyboardOrientation
      : undefined}
    aria-busy={loading || undefined}
    aria-disabled={isDisabled || undefined}
    data-layout={layout}
    data-variant={variant}
    data-size={size}
    data-shape={shape}
    data-disabled={isDisabled || undefined}
    on:keydown={handleToolbarKeydown}
  >
    {#if loading}
      <span class={unstyled ? undefined : "fab-button__section"} aria-live="polite" role="status">
        Loading...
      </span>
    {:else}
      {#each normalizedSections as section, index (section.key)}
        <button
          use:registerSection={index}
          type="button"
          class={unstyled ? section.className : getSectionClasses(section)}
          style={section.style}
          disabled={isDisabled || section.disabled}
          tabindex={toolbarMode ? (index === activeIndex ? 0 : -1) : undefined}
          aria-label={section.ariaLabel}
          data-section={section.key}
          data-section-index={index}
          on:focus={() => {
            if (toolbarMode) activeIndex = index
          }}
          on:click={(event) => handleSectionClick(section, event)}
        >
          {section.content}
        </button>
      {/each}
    {/if}
  </div>
{:else}
  <button
    type="button"
    class={rootClassName}
    style={rootStyle}
    aria-label={ariaLabel}
    aria-busy={loading || undefined}
    disabled={isDisabled}
    data-layout={layout}
    data-variant={variant}
    data-size={size}
    data-shape={shape}
    data-disabled={isDisabled || undefined}
    on:click={handleRootClick}
  >
    {#if loading}
      <span class={unstyled ? undefined : "fab-button__section"} aria-live="polite" role="status">
        Loading...
      </span>
    {:else}
      {#each normalizedSections as section (section.key)}
        <span
          class={unstyled ? section.className : getSectionClasses(section)}
          style={section.style}
          data-section={section.key}
          aria-label={section.ariaLabel}
        >
          {section.content}
        </span>
      {/each}
    {/if}
  </button>
{/if}

// packages/react/src/FabButton.tsx
import { useEffect, useMemo, useRef, useState, type CSSProperties, type KeyboardEvent } from "react"
import {
  getEnabledSectionIndices,
  getFabButtonClasses,
  getFabButtonCssVars,
  getNavigationCommand,
  resolveSectionIndex,
  getSectionClasses,
  normalizeSections
} from "@rezafab/fab-button-core"
import type { FabButtonProps } from "./types"

import "@rezafab/fab-button-styles/style.css"

const mergeStyles = (base: CSSProperties, override?: CSSProperties): CSSProperties => ({
  ...base,
  ...override
})

export const FabButton = ({
  sections,
  variant = "default",
  size = "md",
  shape = "rounded",
  layout = "flex",
  columns,
  rows,
  gap,
  className,
  style,
  unstyled = false,
  disabled = false,
  loading = false,
  ariaLabel,
  keyboardNavigation = "tab",
  keyboardOrientation = layout === "grid" ? "both" : "horizontal",
  loopNavigation = true,
  onClick
}: FabButtonProps) => {
  const normalizedSections = normalizeSections(sections ?? [])
  const hasSectionActions = normalizedSections.some((section) => Boolean(section.onClick))
  const isDisabled = disabled || loading
  const toolbarMode = hasSectionActions && keyboardNavigation === "toolbar"
  const enabledIndices = useMemo(
    () => getEnabledSectionIndices(normalizedSections, isDisabled),
    [normalizedSections, isDisabled]
  )
  const [activeIndex, setActiveIndex] = useState(enabledIndices[0] ?? -1)
  const sectionRefs = useRef<Array<HTMLButtonElement | null>>([])

  useEffect(() => {
    if (!toolbarMode) return
    if (!enabledIndices.length) {
      setActiveIndex(-1)
      return
    }
    if (!enabledIndices.includes(activeIndex)) {
      setActiveIndex(enabledIndices[0])
    }
  }, [activeIndex, enabledIndices, toolbarMode])

  const styleVars = getFabButtonCssVars({
    columns,
    rows,
    gap
  }) as CSSProperties
  const rootClassName = unstyled
    ? className
    : getFabButtonClasses({
        className,
        layout,
        size,
        shape,
        variant,
        disabled: isDisabled,
        loading
      })
  const rootStyle = mergeStyles(styleVars, style)

  const handleToolbarKeyDown = (event: KeyboardEvent<HTMLElement>) => {
    if (!toolbarMode || !enabledIndices.length) return
    const command = getNavigationCommand(event.key, keyboardOrientation)
    if (!command) return

    const target = event.target as HTMLElement | null
    const sectionButton = target?.closest<HTMLButtonElement>("button[data-section-index]")
    if (!sectionButton) return

    const indexValue = Number(sectionButton.dataset.sectionIndex)
    const currentIndex = Number.isNaN(indexValue) ? activeIndex : indexValue
    const nextIndex = resolveSectionIndex({
      command,
      currentIndex,
      enabledIndices,
      loop: loopNavigation
    })
    if (nextIndex === null) return

    event.preventDefault()
    setActiveIndex(nextIndex)
    sectionRefs.current[nextIndex]?.focus()
  }

  if (hasSectionActions) {
    return (
      <div
        className={rootClassName}
        style={rootStyle}
        role={toolbarMode ? "toolbar" : "group"}
        aria-label={ariaLabel}
        aria-orientation={toolbarMode && keyboardOrientation !== "both" ? keyboardOrientation : undefined}
        aria-busy={loading || undefined}
        aria-disabled={isDisabled || undefined}
        data-layout={layout}
        data-variant={variant}
        data-size={size}
        data-shape={shape}
        data-disabled={isDisabled || undefined}
        onKeyDown={handleToolbarKeyDown}
      >
        {loading ? (
          <span
            className={unstyled ? undefined : "fab-button__section"}
            aria-live="polite"
            role="status"
          >
            Loading...
          </span>
        ) : (
          normalizedSections.map((section, index) => (
            <button
              key={section.key}
              ref={(node) => {
                sectionRefs.current[index] = node
              }}
              type="button"
              className={unstyled ? section.className : getSectionClasses(section)}
              style={section.style}
              disabled={isDisabled || section.disabled}
              tabIndex={toolbarMode ? (index === activeIndex ? 0 : -1) : undefined}
              aria-label={section.ariaLabel}
              data-section={section.key}
              data-section-index={index}
              onFocus={() => {
                if (toolbarMode) setActiveIndex(index)
              }}
              onClick={section.onClick}
            >
              {section.content}
            </button>
          ))
        )}
      </div>
    )
  }

  return (
    <button
      type="button"
      className={rootClassName}
      style={rootStyle}
      aria-label={ariaLabel}
      aria-busy={loading || undefined}
      disabled={isDisabled}
      data-layout={layout}
      data-variant={variant}
      data-size={size}
      data-shape={shape}
      data-disabled={isDisabled || undefined}
      onClick={onClick}
    >
      {loading ? (
        <span
          className={unstyled ? undefined : "fab-button__section"}
          aria-live="polite"
          role="status"
        >
          Loading...
        </span>
      ) : (
        normalizedSections.map((section) => (
          <span
            key={section.key}
            className={unstyled ? section.className : getSectionClasses(section)}
            style={section.style}
            data-section={section.key}
            aria-label={section.ariaLabel}
          >
            {section.content}
          </span>
        ))
      )}
    </button>
  )
}
